#+TITLE: CLIM-MODE-LINE
#+AUTHOR: Shozo «szos at posteo dot net»

* CLIM Mode Line
  This is a project to write a dock using CLIM inspired by the emacs and stumpwm mode lines. 

* TODO Fix drag and drop translator
  Drag and drop translator needs fixing, it is unclear why the second argument fails to be aquired.

* TODO Update on window map/unmap
  We want to update the frame whenever a map/unmap event occurs. This should probably be developed as a stumpwm mode line replacement and not a standalone dock/panel. Thus we can say with certainty that the mode line process will be within the same lisp image as stumpwm, and we can use stumpwm directly, and update the mode line directly from stumpwm. This also lets us get an idea of various other aspects, such as groups, heads, etc. 

* TODO Fix Presentation Types
  Presentation types need to be fleshed out. What we want to have happen is, for example, if 
we define a command to move a window to a group, we want to be able to control-click on a window to select it, then click on a group and the window gets sent to that group. This is the same purpose as the drag and drop translator, but we want both working so we can define different behaviores for dragging vs clicking/keystrokes etc. 
