#+TITLE: CLIM-MODE-LINE
#+AUTHOR: Shozo «szos at posteo dot net»

* CLIM Mode Line
  This is a project to write a dock using CLIM inspired by the emacs and StumpWM mode lines. 

** Usage
   Currently the (imo) best way to utilize this modeline is to launch StumpWM as normal and then start a swank/slynk server and connect to it. From the repl evaluate 
   #+BEGIN_SRC lisp
     (in-package :stumpwm)
     (load-module "clim-mode-line")
   #+END_SRC
   - NB! this can take a while if you havent loaded mcclim before, as it will need to be downloaded and compiled. 
   Now that the module is loaded, we need to ensure that 
   1. No other panel applications are running
   2. The mode line is hidden. 
   Now open up a new repl (with sly this is ~sly-mrepl-new~) and evaluate 
   #+BEGIN_SRC lisp
     (in-package :clim-mode-line)
     (run-mode-line)
   #+END_SRC
   At this point the mode line should pop up. 
   - NB! If you kill the mode line process/thread, the built in stumpwm mode line wont return. To kill and restart the clim mode line interrupt the ~run-mode-line~ fuction we ran in our second repl (via =C-c C-c=) and abort the evaluation, then run the stumpwm command ~restart-soft~. This should bring back the built in mode line, and you can follow the steps above to reopen the clim mode line. If you dont have access to the second repl, you can evaluate the following in any repl connected to the image· ~(clim-mode-line::com-quit)~

* Goals
  The initial goal is to get a mode line esq application written in CLIM, which doesnt hang, and allows for CLIM commands to be dispatched via clicking on elements in the mode line.

  After that is completed, we can evaluate adding in a command reading system through the mode line. 

* Todo List
** TODO Fix Crashes
   The mode line soft crashes when commands are executed. Sometimes it functions for a couple commands, other times a single command crashes it. A crash causes no condition to be signalled (they are possibly being caught in the refresh hook function) but rather causes the pane to go white - all output lost. 
** TODO Solve Threading Issues
   It is unclear whether crashes are caused by threading issues. This needs to be investigated and solved. 
