* MODELINE SENSORS DISPLAY

View CPU temperature and fan RPM in the modeline.

** PRE-REQUISITES

Running Linux with ~lm-sensors~ installed.

** USAGE

To load this module, place ~(load-module sensors)~ in your ~.stumpwmrc~.

Sensors information is then available to display in the modeline using ~%S~ in
your modeline config.

As an example, here is my modeline config:

#+BEGIN_SRC common-lisp
  (setf *screen-mode-line-format*
        (list "^3^B%d ^2[%n] ^7%v ^n ^> %S %T"))
#+END_SRC

You can change the default refresh time of 30 seconds with the following
setting.

#+BEGIN_SRC common-lisp
(setf stumpwm.contrib.sensors:*refresh-time* nil)
#+END_SRC

** CAVEATS

This only displays the CPU temperature (~Package id 0~) and the fan RPM
speed. Much more is available with the sensors command. I'd welcome any patches
that made the package more dynamic and configurable in this respect...

Also, I'm very new to Common Lisp, so the code is pretty hacky. I'd welcome any
advice on how to make it better.

** EXTRA

As an extra bonus this module contains the stumpwm command ~sensors~ for viewing
the same information in a message window.
